{% set name = "kokkos-kernels" %}
{% set version = "4.4.01" %}
{% set so_version = "4.4.01" %}
{% set cuda_major = environ.get("cuda_compiler_version", "0.0").split(".")[0]|int %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kokkos/kokkos-kernels/archive/refs/tags/{{ version }}.tar.gz
  sha256: 9f741449f5ace5a7d8a5a81194ff2108e5525d16f08fcd9bb6c9bb4853d7720d
  patches:
    - cuda-cmake.patch  # [cuda_compiler_version != "None"]
build:
  skip: true  # [win]
  string: "cuda{{ cuda_major }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}"  # [cuda_compiler_version != "None"]
  string: "h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}"  # [cuda_compiler_version == "None"]
  number: 0
  run_exports:
    - {{ pin_subpackage('kokkos-kernels') }}
  script_env:
    - KokkosKernels_CUDA_ARGS=-DKokkosKernels_REQUIRE_DEVICES=CUDA  # [cuda_compiler_version != "None"]
    - CUDA_PATH=${PREFIX} # [cuda_compiler_version != "None"]
    - KokkosKernels_CUDA_ARGS=""  # [cuda_compiler_version == "None"]
requirements:
  build:
    - cmake >=3.21.1,<4
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
    - {{ stdlib("c") }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - ninja
  host:
    - kokkos >=4.0.0,<4.5
    # Will get nvcc linker warnings if the cudatoolkit version doesn't match
    - cuda-version {{ environ.get("cuda_compiler_version") }}.*  # [cuda_compiler_version != "None"]
    {% if cuda_major == 11 %}
    - cudatoolkit {{ environ.get("cuda_compiler_version") }}.*
    {% endif %}
    {% if cuda_major == 12 %}
    - cuda-cudart-dev
    - cuda-driver-dev   # [not win]
    - libcublas-dev
    - libcusparse-dev
    - libcusolver-dev
    {% endif %}
  run:
    - kokkos >=4.0.0,<4.5
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version not in (undefined, 'None')]
    {% if cuda_major == 11 %}
    - cudatoolkit {{ environ.get("cuda_compiler_version") }}.*
    {% endif %}
    {% if cuda_major >= 12 %}
    - cuda-cudart
    - libcufft
    - libcublas
    {% endif %}


test:
  source_files:
    - example/batched_solve
  commands:
    - $CXX example/batched_solve/team_GMRES.cpp -o team_GMRES -std=c++17 -I$PREFIX/include -L$PREFIX/lib -lkokkoscontainers -lkokkoscore -lkokkoskernels -fopenmp
  # Lots more CMake files; just checking for one
    - test -f $PREFIX/lib/cmake/KokkosKernels/KokkosKernelsConfig.cmake  # [unix]
  # Testing explicitly for all shared libs, but not links
    - test -f $PREFIX/lib/libkokkoskernels.so  # [linux]
    - test -f $PREFIX/lib/libkokkoskernels.dylib  # [osx]
  # There are lots more headers; only test for one.
    - test -f $PREFIX/include/KokkosKernels_Handle.hpp  # [unix]
  requires:
    - {{ compiler('cxx') }}
    
about:
  home: https://kokkos.org/
  summary: >
    Kokkos Kernels is a software library of linear algebra and graph algorithms used across many HPC applications to 
    achieve best (not just good) performance on every architecture.
  description: >
    The baseline version of this library is written using 
    the Kokkos Core programming model for portability and good performance. The library has architecture-specific 
    optimizations or uses vendor-specific versions of these mathematical algorithms where needed. This reduces the amount 
    of architecture-specific software that an application team potentially needs to develop, thus further reducing their  
    (modification cost)to achieve “best in class” performance.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://kokkos.org/api-kernels/
  dev_url: https://github.com/kokkos/kokkos-kernels

extra:
  recipe-maintainers:
    - BastianZim
    - vincentmr
